# Generated by Django 6.0.3 on 2026-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=15, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('categories', models.CharField(choices=[('politics', 'Политика'), ('economy', 'Экономика'), ('technology', 'Технологии'), ('sports', 'Спорт'), ('world', 'Мир'), ('society', 'Общество'), ('culture', 'Культура'), ('science', 'Наука'), ('health', 'Здоровье'), ('auto', 'Авто'), ('other', 'Другое')], max_length=25, verbose_name='Kатегории')),
            ],
        ),
    ]
