# Generated by Django 6.0.3 on 2026-04-01 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vievs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsModel',
        ),
        migrations.RenameModel(
            old_name='Vievs',
            new_name='VievsModel',
        ),
    ]
